// path: server/src/utils/draftGenerator.ts
// Generates a formal complaint letter from complaint data.
// Used when complaint is created — saved to autoDraft field.

interface DraftInput {
  name:        string;
  complaintId: string;
  category:    string;
  description: string;
  date:        string;
}

export function generateDraft(data: DraftInput): string {
  return `
TO,
The Concerned Authority
Legal Grievance Department

Date: ${data.date}
Reference No: ${data.complaintId}

SUBJECT: FORMAL COMPLAINT REGARDING ${data.category.toUpperCase()}

Respected Sir/Madam,

I, ${data.name}, hereby submit this formal complaint for your immediate attention
and appropriate action.

NATURE OF COMPLAINT:
Category: ${data.category}

DETAILS OF THE COMPLAINT:
${data.description}

I request your office to:
1. Register this complaint under the appropriate section
2. Initiate necessary investigation at the earliest
3. Provide me with a reference number for tracking
4. Take prompt legal action as per applicable laws

I am prepared to provide any additional information or documentation required
to support this complaint.

Yours faithfully,
${data.name}

[Reference ID: ${data.complaintId}]

---
DISCLAIMER: This is a system-generated formal complaint draft.
Please review and modify before submission to authorities.
Generated by NEETHIVAAN — AI-Driven Legal Grievance Management System
  `.trim();
}
